### ISSUE TITLE
Adding images dynamically

### ISSUE THREAD

**Issue by preethamnagesh8** [MaxRcd/open-docxtemplater-image-module#1]
How do I add images dynamically ?

Use Case - 
1. I have a UI in which the user selects the images dynamically.
2. When the report is generated, the word must have the images.

But the issue is, how to place {%image01}, {%image02} tags ?
And they need to be in different places of the document.

**Comment by MaxRcd** [comment]
Hi @preethamnagesh8,

Have you figured out the solution by yourself in the meantime? I didn't turn the notifications on.

You can place the {%image} tags anywhere you want in the document. You can also use {#myloop}{%image}{/myloop} for looping several images. As described here: https://docxtemplater.readthedocs.io/en/latest/tag_types.html#loops

Didn't test this by myself but I'm confident it works.

Regards.
