### ISSUE TITLE
error TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by jonnathanlopes** [MaxRcd/open-docxtemplater-image-module#4]
How Can i solve this issue TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.

**Comment by MaxRcd** [comment]
Hi jonnathanlopes,

I would be happy to help, however without any explanation and code I fear I cannot do anything for you.

Regards,
Maxime
